apiVersion: v1
entries:
  bis-app:
  - apiVersion: v2
    appVersion: "1.2"
    created: "2023-12-20T02:09:44.299806+01:00"
    description: sample nginx deployment
    digest: 01a93a81a0b9ad97d997974d6b177c3351bcb004447a3a5e384b9cca4c1ce8ff
    name: bis-app
    type: application
    urls:
    - bis-app-1.2.tgz
    version: "1.2"
  - apiVersion: v2
    appVersion: "1.1"
    created: "2023-12-20T02:09:44.299682+01:00"
    description: sample nginx deployment
    digest: 6b7230f96b8b662aa58668abace6d5548210d8aa57369b667719e02bc5d1ed27
    name: bis-app
    type: application
    urls:
    - bis-app-1.1.tgz
    version: "1.1"
generated: "2023-12-20T02:09:44.29944+01:00"
