apiVersion: v1
entries:
  bis-app:
  - apiVersion: v2
    appVersion: "1"
    created: "2023-12-19T17:47:42.425691+01:00"
    description: sample nginx deployment
    digest: e92e231726f83a8cd9da29ade7caa3f20a1eb146c70c82727da2ba28a149c877
    name: bis-app
    type: application
    urls:
    - bis-app-1.tgz
    version: "1"
generated: "2023-12-19T17:47:42.425376+01:00"
